# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGL107VYYjmWzx2oi6GmOmM3c1SUbfFx
"""

import streamlit as st
from predict import predict

st.title("Credit Risk Predictor")

age = st.number_input("Age")
income = st.number_input("Monthly Income")

if st.button("Predict"):
    data = [0, age, 0, 0, income, 0, 0, 0, 0, 0] 
    result = predict(data)
    st.write("Default Probability:", result)
