# -*- coding: utf-8 -*-
"""llm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BR7occ5Tm-K1WhxxOQrw0fcSelc-mce2
"""

# LLM

from transformers import pipeline

llm = pipeline("text-generation", model="google/flan-t5-base")

def generate(query, context):
    prompt = f"Context: {context}\nQuestion: {query}"
    return llm(prompt)[0]['generated_text']