# -*- coding: utf-8 -*-
"""predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsA9BjmXqMaXyHF8NX230-bnC0ewIOLb
"""

import torch
import joblib
import numpy as np
from model import Model

scaler = joblib.load("scaler.pkl")

model = Model(10)  # adjust input dim
model.load_state_dict(torch.load("model.pth"))
model.eval()

def predict(input_data):
    input_scaled = scaler.transform([input_data])
    input_tensor = torch.tensor(input_scaled, dtype=torch.float32)
    return model(input_tensor).item()

